### ISSUE TITLE
Include Rmd, use out-of-the box fonts, transparent plot backgrounds

### ISSUE THREAD

**Issue by jsta** [PoisotLab/PLPT#1]
This is a great looking template! 

Thought I would share my modified version (https://github.com/jsta/PLPT) that includes an `Rmd` file and  uses Ubuntu system fonts (I couldn't get the `Noto` fonts to work). I also added slides showing how to include R plots with a transparent background to deal with the off-white template color.

**Comment by tpoisot** [comment]
Awesome! I know that Noto are not always easy to install, so I like the idea of default fonts. I'm working on a version with options to change the fonts when compiling. 

Feel free to submit a pull request, I think it would be useful to see the info on R plots.
