### ISSUE TITLE
visual counter

### ISSUE THREAD

**Issue by anabento** [PoisotLab/PLPT#2]
Hi 
Sorry for the undetailed message. I have downloaded all the sty and tex files that were preciously giving e errors.. but I still have loads of errors. But it seems to me the errors aren't even related to the visual counter (see png)...
I know this is a big ask... but would you be able to write a simple latex file that create slides with the visual counter?
Thank you!
Ana
<img width="1280" alt="screenshot 2018-11-22 12 11 24" src="https://user-images.githubusercontent.com/10956915/48916328-c46b6600-ee4f-11e8-9847-892ea926a92c.png">

**Comment by tpoisot** [comment]
Are you using latexmake to compile?
